quickdashapi/api/urls.py
from django.urls import path

from .views import UserView, EntriesView, EntryDetailView, SpecificVideoView


app_name = "api"

urlpatterns = [
    # Entries endpoints
    path('entries/', EntriesView.as_view(), name='EntriesListEndpoint'),  # "Get list of all entries"
    path('entries/<int:pk>/', EntryDetailView.as_view(), name='EntryDetailEndpoint'),  # "Get specific entry by id"
    path('entries/<int:user>/last/', SpecificVideoView.as_view(), name='LastVideoEndpoint'),  # "Get users last video overview"
    path('entries/<int:user>/<str:date>/', SpecificVideoView.as_view(), name='FilteredDateVideoEndpoint'),  # "Get specific user video result using date"
    path('entries/<int:user>/<str:title>/', SpecificVideoView.as_view(), name='FilteredTitleVideoEndpoint'),  # "Get specific user video result using title"
    path('entries/<int:user>/<str:date>/<str:title>/', SpecificVideoView.as_view(), name='DateTitleFilteredVideoEndpoint'),  # "Get specific video result using date and title"

    # Users endpoints
    path('users/<int:pk>/', UserView.as_view(), name='UserDetailEndpoint'),  # "Get specific user data by id",
]

quickdashapi/ceretaidash/urls.py
from django.urls import path, include

from .views import LastProcessedEntry, EntryDetailResults


app_name = 'ceretaidash'

urlpatterns = [
    path('', LastProcessedEntry.as_view(), name='general'),
    path('user/', include('django.contrib.auth.urls')),
    path('detailed-results/<str:date>', EntryDetailResults.as_view(), name='results_detail'),
]

quickdashapi/quickdashapi/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('ceretaidash.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('mainquickapi.urls')),
]

quickdashapi/quickdashapi_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('ceretaidash.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
]

quickdashapi/ceretaidash/models.py
from django.db import models

# Create your models here.

quickdashapi/ceretaidash/views.py
import base64
import datetime
import json
import io
import math
import requests
import urllib

import matplotlib.pyplot as plt

from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import View


def create_pie_chart_data(response_data) -> dict:
    """Creating and populating detailed entry data analysis for pie charts

    Parameters
    ----------
    response_data : dict
        Data retrieved from api

    Returns
    -------
    dict
        Dictionary with calculated total video length and created pie charts for speech and screen
    """
    if len(response_data) == 1:
        total_length = datetime.timedelta(seconds=response_data['video_1']['speech_time']['total_length'])
        if 'speech_time' in response_data['video_1']:
            all_speech_time_data = response_data['video_1']['speech_time']
            speech_labels = []
            speech_sizes = []

            total_speech_perc = math.ceil(
                (all_speech_time_data['total_speech'] * 100) / all_speech_time_data['total_length'])
            total_no_speech_perc = int(
                ((all_speech_time_data['total_length'] - all_speech_time_data['total_speech']) * 100) /
                all_speech_time_data['total_length'])
            speech_labels.append('No speech')
            speech_sizes.append(total_no_speech_perc)
            for name, value in all_speech_time_data.items():
                if name == 'speech_f':
                    speech_labels.append('Woman')
                    speech_sizes.append(int((value * 100) / total_speech_perc))
                elif name == 'speech_m':
                    speech_labels.append('Man')
                    speech_sizes.append(int((value * 100) / total_speech_perc))

            speech_chart = create_pie_chart(labels=speech_labels, sizes=speech_sizes)

        if 'face_data' in response_data['video_1']:
            all_face_data = response_data['video_1']['face_data']
            screen_labels = []
            screen_sizes = []

            for name, value in all_face_data.items():
                if name == 'screen_f':
                    screen_labels.append('Woman')
                    screen_sizes.append(value)
                elif name == 'screen_m':
                    screen_labels.append('Man')
                    screen_sizes.append(value)
                elif name == 'screen_n':
                    screen_labels.append('Undetermined')
                    screen_sizes.append(value)

            screen_chart = create_pie_chart(labels=screen_labels, sizes=screen_sizes)
    else:
        total_seconds = 0

        # Screen presence lists
        screen_labels = []
        screen_sizes = []
        label_size_screen_dict = {}
        woman_sizes = 0
        man_sizes = 0
        undetermined_sizes = 0

        # Speech time lists
        speech_labels = []
        speech_sizes = []
        label_size_speech_dict = {}
        total_speech = 0
        woman_speech = 0
        man_speech = 0
        no_speech = 0

        video_amount = len(response_data)
        for video in response_data:

            # Gathering screen presence data
            for name, value in response_data[video]['face_data'].items():
                if name == 'screen_f':
                    label_size_screen_dict['Woman'] = 0
                    woman_sizes += value
                elif name == 'screen_m':
                    label_size_screen_dict['Man'] = 0
                    man_sizes += value
                elif name == 'screen_n':
                    label_size_screen_dict['Undetermined'] = 0
                    undetermined_sizes += value

            # Gathering speech time data
            all_speech_time_data = response_data[video]['speech_time']
            total_seconds += all_speech_time_data['total_length']
            total_speech_perc = math.ceil(
                (all_speech_time_data['total_speech'] * 100) / all_speech_time_data['total_length'])
            total_no_speech_perc = math.ceil(
                ((all_speech_time_data['total_length'] - all_speech_time_data['total_speech']) * 100) /
                all_speech_time_data['total_length'])
            label_size_speech_dict['No speech'] = 0
            total_speech += total_speech_perc
            no_speech += total_no_speech_perc
            for name, value in response_data[video]['speech_time'].items():
                if name == 'speech_f':
                    label_size_speech_dict['Woman'] = 0
                    woman_speech += int((value * 100) / total_speech_perc)
                elif name == 'speech_m':
                    label_size_speech_dict['Man'] = 0
                    man_speech += int((value * 100) / total_speech_perc)

        for name, value in label_size_speech_dict.items():
            if name == 'Woman':
                label_size_speech_dict['Woman'] = woman_speech // video_amount
            elif name == 'Man':
                label_size_speech_dict['Man'] = man_speech // video_amount
            elif name == 'No speech':
                label_size_speech_dict['No speech'] = no_speech // video_amount

        for gender, percentage in label_size_speech_dict.items():
            if gender == 'Woman':
                speech_labels.append('Woman')
                speech_sizes.append(percentage)
            elif gender == 'Man':
                speech_labels.append('Man')
                speech_sizes.append(percentage)
            elif gender == 'No speech':
                speech_labels.append('Undetermined')
                speech_sizes.append(percentage)

        speech_chart = create_pie_chart(labels=speech_labels, sizes=speech_sizes)

        # Processing screen data
        for name, value in label_size_screen_dict.items():
            if name == 'Woman':
                label_size_screen_dict['Woman'] = woman_sizes // video_amount
            elif name == 'Man':
                label_size_screen_dict['Man'] = man_sizes // video_amount
            elif name == 'Undetermined':
                label_size_screen_dict['Undetermined'] = undetermined_sizes // video_amount
        for gender, percentage in label_size_screen_dict.items():
            if gender == 'Woman':
                screen_labels.append('Woman')
                screen_sizes.append(percentage)
            elif gender == 'Man':
                screen_labels.append('Man')
                screen_sizes.append(percentage)
            elif gender == 'Undetermined':
                screen_labels.append('Undetermined')
                screen_sizes.append(percentage)

        h, m, s = str(datetime.timedelta(seconds=total_seconds)).split(':')
        total_length = '{}h {}m {}s'.format(h, m, s)

        screen_chart = create_pie_chart(labels=screen_labels, sizes=screen_sizes)
    return {
        'total_length': total_length,
        'speech_chart': speech_chart,
        'screen_chart': screen_chart,
    }


def create_bar_chart_data(response_data):
    """Creating and populating detailed entry data analysis for bar chart

    Parameters
    ----------
    response_data : dict
        Data retrieved from api

    Returns
    -------
    dict
        Dictionary created bar chart for age
    """

    videos_amount = len(response_data)
    if videos_amount == 1:
        age_labels = []
        age_sizes = []
        all_age_data = response_data['video_1']['age_all_data']
        for key, value in all_age_data.items():
            if key == 'a_0':
                age_labels.append('1-14')
                age_sizes.append(value)
            if key == 'a_15':
                age_labels.append('15-29')
                age_sizes.append(value)
            if key == 'a_30':
                age_labels.append('30-44')
                age_sizes.append(value)
            if key == 'a_45':
                age_labels.append('45-59')
                age_sizes.append(value)
            if key == 'a_60':
                age_labels.append('60-74')
                age_sizes.append(value)
            if key == 'a_75':
                age_labels.append('75-89')
                age_sizes.append(value)
            if key == 'a_90':
                age_labels.append('90 >')
                age_sizes.append(value)

        age_chart = create_bar_chart(labels=age_labels, sizes=age_sizes)
    else:
        age_labels = []
        age_sizes = []
        label_size_age_dict = {}
        a_0 = 0
        a_15 = 0
        a_30 = 0
        a_45 = 0
        a_60 = 0
        a_75 = 0
        a_90 = 0
        for video in response_data:
            all_age_data = response_data[video]['age_all_data']
            for key, value in all_age_data.items():
                if key == 'a_0':
                    label_size_age_dict['1-14'] = 0
                    a_0 += value
                if key == 'a_15':
                    label_size_age_dict['15-29'] = 0
                    a_15 += value
                if key == 'a_30':
                    label_size_age_dict['30-44'] = 0
                    a_30 += value
                if key == 'a_45':
                    label_size_age_dict['45-59'] = 0
                    a_45 += value
                if key == 'a_60':
                    label_size_age_dict['60-74'] = 0
                    a_60 += value
                if key == 'a_75':
                    label_size_age_dict['75-89'] = 0
                    a_75 += value
                if key == 'a_90':
                    label_size_age_dict['90 >'] = 0
                    a_90 += value
        for age_cat, age in label_size_age_dict.items():
            if age_cat == '1-14':
                label_size_age_dict['1-14'] = a_0 // videos_amount
            if age_cat == '15-29':
                label_size_age_dict['15-29'] = a_15 // videos_amount
            if age_cat == '30-44':
                label_size_age_dict['30-44'] = a_30 // videos_amount
            if age_cat == '45-69':
                label_size_age_dict['45-59'] = a_45 // videos_amount

quickdashapi/ceretaidash/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <script src="{% static 'ceretaidash/js/jquery-3.5.1.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'ceretaidash/css/main.css' %}">
    <script type="text/javascript" src="{% static 'ceretaidash/js/main.js' %}"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <script>
        $(function() {
          $('#date-picker').daterangepicker({
            "locale": {
                "format": "YYYY-MM-DD",
            },
            }, function(start, end, label) {
              console.log('New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')');
            });
        });
    </script>
</head>
<body>
  <header>{% include "header.html" %}</header>
  <main class="col-lg-10 offset-lg-1">
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

quickdashapi/ceretaidash/templates/detailed_view.html
{% extends 'base.html' %}

{% block title %}Diversity results{% endblock %}

{% block content %}
    <div class="main-detail-table">
        <h3 class="detail-title">Diversity results</h3>
        <div class="period-status">Showing results for period {{ entry_date }}</div>
        <div class="row period-filter">
            <form class="filter-picker col" action="{% url 'api:EntriesListEndpoint' %}" method="get">
                <div class="form-row col">
                    <div class="form-group col-md-3">
                        <label for="date-picker">See results from the period of</label>
                        <input type="text" class="form-control" id="date-picker" placeholder="Date range">
                    </div>
                    <div class="form-group col-md-3 offset-md-1">
                        <label for="title-picker">Filter on title</label>
                        <input class="form-control" id="title-picker" placeholder="e.g News">
                    </div>
                    <button class="filter-button col-md-2 offset-md-2" type="submit" class="btn btn-primary">show results</button>
                </div>
            </form>
        </div>
        {% if not programms_amount %}
            <div class="no-results col-lg-12 text-center">
                <h1>No results for this time period</h1>
            </div>
        {% else %}
            <div class="prog_info row">
                <span><b>Ammount of programmes:</b> {{ programms_amount }}</span>
                <span><b>Total length:</b> {{ total_length }}</span>
            </div>
            <div class="representation-wrapper">
                <h4 class="repr-title">Representation</h4>
            </div>
            <hr>
            <div class="detailed-results">
                <div class="title-wrapper">
                    <p class="detailed-title">Gender</p>
                </div>
                <div class="row charts-imgs text-center">
                    <div class="screen-presence col-lg-6">
                        <h4>Screen presence</h4>
                        <img class="screen-img" src="data:image/png;base64,{{ screen_chart }}" width="500px">
                    </div>
                    <div class="speaking-time col-lg-6">
                        <h4>Speaking time</h4>
                        <img class="speaking-img" src="data:image/png;base64,{{ speech_chart }}" width="500px">
                    </div>
                </div>
            </div>
            <div class="detailed-results">
                <div class="title-wrapper">
                    <p class="detailed-title">Age</p>
                </div>
                <div class="row charts-imgs text-center">
                    <div class="age-distribution col-lg-6">
                        <h4>Age distribution</h4>
                        <img class="age-distribution-img" src="data:image/png;base64,{{ bar_chart }}" width="500px">
                    </div>
                    <div class="speaking-time col-lg-6">
                        <h4>Average age per gender</h4>
                        <div class="row justify-content-around avg-ages">
                            <div class="woman-age col-md-3">
                                <p>Womens are</br>
                                <span class="avg-f"><b>{{ woman_avg_age }}</b></span></br>
                                y/o on average</p>
                            </div>
                            <div class="man-age col-md-3">
                                <p>Men are</br>
                                <span class="avg-m"><b>{{ man_avg_age }}</b></span></br>
                                y/o on average</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

quickdashapi/ceretaidash/templates/general_view.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
  <div class="welcome-title">
    <h1>Welcome, {{ user.username }}.</h1>
  </div>
  {% endif %}
  <div class="last-results">
    {% if not last_result %}
      <h4 class="result-title">{{ 'yesterday\'s diversity overview'|upper }}</h4>
    {% else %}
      <h4 class="result-title">{{ 'Diversity overview for '|upper }}{{ entry_date }}</h4>
    {% endif %}
    <span><b>Ammount of programmes:</b> {{ programms_amount }}</span>
    <span><b>Total length:</b> {{ total_length }}</span>
    <div class="row charts-imgs text-center">
      <div class="screen-presence col-lg-6">
        <h4>Screen presence</h4>
        <img class="screen-img" src="data:image/png;base64,{{ screen_chart }}" width="500px">
      </div>
      <div class="speaking-time col-lg-6">
        <h4>Speaking time</h4>
        <img class="speaking-img" src="data:image/png;base64,{{ speech_chart }}" width="500px">
      </div>
    </div>
  </div>
  <div class="all-results-button-wrapper">
    <button class="btn-primary all-results-button"><a class="detail-results-link" href="{% url 'ceretaidash:results_detail' date=entry_date %}">{{ 'see all results'|upper }}</a></button>
  </div>
  <div class="row justify-content-between status-subscripton-block">
    <div class="general-status col-lg-5">
      <h4 class="status-title">{{ 'status'|upper }}</h4>
      <p class="status-info">{{ programms_amount }} programmes went through diversity analysis {% if not last_result %}yesterday{% else %}{{ entry_date }}{% endif %}.</p>
    </div>
    <div class="general-subscription col-lg-5">
      <div class="sub-info text-center">{{ total_hours }} hours per month</div>
      <h4 class="sub-title">{{ 'subscription'|upper }}</h4>
      <p class="sub-left">You have {{ hours_left }} hours left ot analyze this month</p>
    </div>
  </div>
  <div class="col news-block text-left">
    <h4 class="news-title">{{ 'news'|upper }}</h4>
    <div class="row col-lg-11">
      <div class="news-date">7/9/2020</div><div class="new-title offset-lg-2">News one</div>
    </div>
    <hr>
    <div class="row col-lg-11">
      <div class="news-date">1/9/2020</div><div class="new-title offset-lg-2">News two</div>
    </div>
    <hr>
  </div>
{% endblock %}

quickdashapi/ceretaidash/templates/header.html
{% load static %}
<a href="{% url 'ceretaidash:general' %}"><img class="logo" src="{% static 'ceretaidash/img/highres_ceretai_logo.png' %}"></a>
<div class="navbar">
    <div class="results-header">Diversity results</div>
    <div>|</div>
    {% if user.is_authenticated %}
        <div class="account-header" id="{{ user.user_id }}" >Account: {{ user.username }}</div>
        <div class="logout"><a href="{% url 'ceretaidash:logout' %}">Log Out</a></div>
    {% endif %}
</div>